FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build ui

FROM nginx:alpine

WORKDIR /var/www/html

COPY --from=builder /app/dist/apps/ui /var/www/html/

EXPOSE 80
CMD nginx -g 'daemon off;'
